embeddings {
  tensor_name: "unique_id:00029"
  metadata_path: "00029/unique_id/metadata.tsv"
  tensor_path: "00029/unique_id/tensors.tsv"
}
embeddings {
  tensor_name: "day_of_week:00029"
  metadata_path: "00029/day_of_week/metadata.tsv"
  tensor_path: "00029/day_of_week/tensors.tsv"
}
embeddings {
  tensor_name: "month:00029"
  metadata_path: "00029/month/metadata.tsv"
  tensor_path: "00029/month/tensors.tsv"
}
