services:
  - type: web
    name: product-demand-forecasting-api
    env: python
    rootDir: backend
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: FRONTEND_ORIGINS
        sync: false
